# Lineare Unabhängigkeit von Vektoren

Eine Linearkombination 
$\sum_{i=1}^n a_i v_i = 0$ heißt **triviale Darstellung des Nullvektors** durch $v_1 , . . . , v_n$, wenn $a_i = 0$ für alle $1 <= i <= n$ ist.

Falls mindestens ein $a_i != 0$ ist, so ist $\sum_{i=1}^n a_i v_i = 0$ eine **nicht triviale Darstellung des Nullvektors** durch durch $v_1 , . . . , v_n$.

Die Vektoren $v_1 , . . . v_n \in V$ heißen linear abhängig, falls es eine nicht-triviale Darstellung des Nullvektors durch $v_1 , . . . , v_n$ gibt.


## Beispiel

Behauptung: $v_1, v_2, v_3$ sind linear unabhängig
Beweis: Seien $a_1, a_2, a_3 \in \mathbb{R}$ so dass 

\begin{equation}
a_1 \begin{pmatrix}2 \\ 1 \\ 2 \end{pmatrix} + a_2 \begin{pmatrix}3 \\ 1 \\ 4 \end{pmatrix} + a_3 \begin{pmatrix}2 \\ 3 \\ 1 \end{pmatrix} = \begin{pmatrix}0 \\ 0 \\ 0 \end{pmatrix}
\end{equation}

Dann ist $\begin{pmatrix}a_1 \\ a_2 \\ a_3 \end{pmatrix}$ die Lösung des linearen Gleichungssystems 
\begin{equation}
\begin{pmatrix}1 & 3 & 2 \\ 1 & 1 & 3 \\ 2 & 4 & 1 \end{pmatrix} \begin{pmatrix}x_1 \\ x_2 \\ x_3 \end{pmatrix} = \begin{pmatrix}0 \\ 0 \\ 0 \end{pmatrix}
\end{equation}

### Vorgehen

Überführe Koeffizientenmatrix in Treppennormalform. Resultat darf keine Nullzeilen enthalten --> GLS lösbar. Lösung ist der Nullvektor. 


In [1]:
import numpy as np
np.set_printoptions(precision=3)
#define elementary operations on matrices

# swap rows P_ij
def P(i, j, matrix):
    matrix_p = np.copy(matrix)
    matrix_p[i-1] = matrix[j-1]
    matrix_p[j-1] = matrix[i-1]
    print("---------")
    print("P", i , j)
    print(matrix_p)
    print("---------")
    return matrix_p

# add value row j * var to row i (T_ij(var))
def T(i, j, var, matrix):
    matrix_t = np.copy(matrix)
    matrix_t[i-1] = matrix_t[i-1] + matrix[j-1] * var
    print("---------")
    print("T", i, j, var)
    print(matrix_t)
    print("---------")
    return matrix_t

# multiply row i with var (D_i(var))
def D(i, var, matrix):
    matrix_d = np.copy(matrix)
    matrix_d[i-1] = matrix_d[i-1] * var
    print("---------")
    print("D", i , var)
    print(matrix_d)
    print("---------")
    return matrix_d
    
    

In [2]:
koeff_matrix = np.array([[1, 3, 2], [1, 2, 3], [2,4,1]], dtype='float')
print(koeff_matrix)

koeff_matrix = T(2,1,-1, koeff_matrix)
koeff_matrix = T(3,1,-2, koeff_matrix)
koeff_matrix = D(2, -1, koeff_matrix)
koeff_matrix = D(3,-0.5, koeff_matrix)
koeff_matrix = T(1,2,-3, koeff_matrix)
koeff_matrix = T(3,2,-1, koeff_matrix)
koeff_matrix = D(3, (1/2.5), koeff_matrix)
koeff_matrix = T(2,3,1, koeff_matrix)
koeff_matrix = T(1,3,-5, koeff_matrix)

print("\nResultat")
print(koeff_matrix)

print("\nCross check with linsolver")
koeff_matrix = np.array([[1, 3, 2], [1, 2, 3], [2,4,1]], dtype='float')
zeros = np.array([0, 0, 0])
x = np.linalg.solve(koeff_matrix, zeros)
print(x)

[[ 1.  3.  2.]
 [ 1.  2.  3.]
 [ 2.  4.  1.]]
---------
('T', 2, 1, -1)
[[ 1.  3.  2.]
 [ 0. -1.  1.]
 [ 2.  4.  1.]]
---------
---------
('T', 3, 1, -2)
[[ 1.  3.  2.]
 [ 0. -1.  1.]
 [ 0. -2. -3.]]
---------
---------
('D', 2, -1)
[[ 1.  3.  2.]
 [-0.  1. -1.]
 [ 0. -2. -3.]]
---------
---------
('D', 3, -0.5)
[[ 1.   3.   2. ]
 [-0.   1.  -1. ]
 [-0.   1.   1.5]]
---------
---------
('T', 1, 2, -3)
[[ 1.   0.   5. ]
 [-0.   1.  -1. ]
 [-0.   1.   1.5]]
---------
---------
('T', 3, 2, -1)
[[ 1.   0.   5. ]
 [-0.   1.  -1. ]
 [ 0.   0.   2.5]]
---------
---------
('D', 3, 0.4)
[[ 1.  0.  5.]
 [-0.  1. -1.]
 [ 0.  0.  1.]]
---------
---------
('T', 2, 3, 1)
[[ 1.  0.  5.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
---------
---------
('T', 1, 3, -5)
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
---------

Resultat
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]

Cross check with linsolver
[ 0.  0.  0.]


Das Resultat ist die Umformung in Treppennormalform ist die Einheitsmatrix. Das GLS ist somit Lösbar da
$\begin{pmatrix}a_1 \\ a_2 \\ a_3 \end{pmatrix} * \begin{pmatrix}1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{pmatrix} = \begin{pmatrix}0 \\ 0 \\ 0 \end{pmatrix}$ 


## Übung 1

Untersuche ob 
\begin{equation}
\begin{pmatrix}1 \\ 0 \\ -1 \\ 1 \end{pmatrix}, \begin{pmatrix}1 \\ -1 \\ 1 \\ 3 \end{pmatrix}, \begin{pmatrix}-2 \\ 3 \\ 3 \\ 0 \end{pmatrix} \in \mathbb{R^4}
\end{equation}
linear unabhängig sind.

In [22]:
koeff_matrix = np.array([[1, 1, -2], [0, -1, 3], [-1, 1, 3], [1, 3, 0]], dtype='float')
print(koeff_matrix)


koeff_matrix = P(4,1, koeff_matrix)
koeff_matrix = T(1,2,3, koeff_matrix)
koeff_matrix = T(3,1,1, koeff_matrix)
koeff_matrix = T(4,1,-1, koeff_matrix)
koeff_matrix = T(4,2,1, koeff_matrix)
koeff_matrix = T(3,2,1, koeff_matrix)
koeff_matrix = D(2,-1, koeff_matrix)
koeff_matrix = D(3,float(1.0/15.0), koeff_matrix)
koeff_matrix = T(4,3,8, koeff_matrix)
koeff_matrix = T(2,3,3, koeff_matrix)
koeff_matrix = T(1,3,-9, koeff_matrix)

print("\nResultat")
print(koeff_matrix)

[[ 1.  1. -2.]
 [ 0. -1.  3.]
 [-1.  1.  3.]
 [ 1.  3.  0.]]
---------
('P', 4, 1)
[[ 1.  3.  0.]
 [ 0. -1.  3.]
 [-1.  1.  3.]
 [ 1.  1. -2.]]
---------
---------
('T', 1, 2, 3)
[[ 1.  0.  9.]
 [ 0. -1.  3.]
 [-1.  1.  3.]
 [ 1.  1. -2.]]
---------
---------
('T', 3, 1, 1)
[[  1.   0.   9.]
 [  0.  -1.   3.]
 [  0.   1.  12.]
 [  1.   1.  -2.]]
---------
---------
('T', 4, 1, -1)
[[  1.   0.   9.]
 [  0.  -1.   3.]
 [  0.   1.  12.]
 [  0.   1. -11.]]
---------
---------
('T', 4, 2, 1)
[[  1.   0.   9.]
 [  0.  -1.   3.]
 [  0.   1.  12.]
 [  0.   0.  -8.]]
---------
---------
('T', 3, 2, 1)
[[  1.   0.   9.]
 [  0.  -1.   3.]
 [  0.   0.  15.]
 [  0.   0.  -8.]]
---------
---------
('D', 2, -1)
[[  1.   0.   9.]
 [ -0.   1.  -3.]
 [  0.   0.  15.]
 [  0.   0.  -8.]]
---------
---------
('D', 3, 0.06666666666666667)
[[ 1.  0.  9.]
 [-0.  1. -3.]
 [ 0.  0.  1.]
 [ 0.  0. -8.]]
---------
---------
('T', 4, 3, 8)
[[ 1.  0.  9.]
 [-0.  1. -3.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]
---------
----

Das Resultat zeigt, dass das GLS lösbar ist --> Rang(3). Die Vektoren sind damit linear unabhängig.

### Übung 2

Untersuche ob 
\begin{equation}
\begin{pmatrix} 1 & 3 \\ 2 & 1 \end{pmatrix}, \begin{pmatrix} -2 & -1  \\ 1 & 4 \end{pmatrix}, \begin{pmatrix}1 & 0 \\ 2 & 1\end{pmatrix} \in M_{22}(\mathbb{R})
\end{equation}
linear unabhängig sind.

In [31]:
koeff_matrix = np.array([[1, -2, 1], [3, -2, 0], [2, 1, 2], [1, 4, 1]], dtype='float')
print(koeff_matrix)

koeff_matrix = T(2,1,-3, koeff_matrix)
koeff_matrix = T(3,1,-2, koeff_matrix)
koeff_matrix = T(4,1,-1, koeff_matrix)
koeff_matrix = P(4,2, koeff_matrix)
koeff_matrix = D(2,(1.0/6.0), koeff_matrix)
koeff_matrix = T(1,2,2, koeff_matrix)

[[ 1. -2.  1.]
 [ 3. -2.  0.]
 [ 2.  1.  2.]
 [ 1.  4.  1.]]
---------
('T', 2, 1, -3)
[[ 1. -2.  1.]
 [ 0.  4. -3.]
 [ 2.  1.  2.]
 [ 1.  4.  1.]]
---------
---------
('T', 3, 1, -2)
[[ 1. -2.  1.]
 [ 0.  4. -3.]
 [ 0.  5.  0.]
 [ 1.  4.  1.]]
---------
---------
('T', 4, 1, -1)
[[ 1. -2.  1.]
 [ 0.  4. -3.]
 [ 0.  5.  0.]
 [ 0.  6.  0.]]
---------
---------
('P', 4, 2)
[[ 1. -2.  1.]
 [ 0.  6.  0.]
 [ 0.  5.  0.]
 [ 0.  4. -3.]]
---------
---------
('D', 2, 0.16666666666666666)
[[ 1. -2.  1.]
 [ 0.  1.  0.]
 [ 0.  5.  0.]
 [ 0.  4. -3.]]
---------
---------
('T', 1, 2, 2)
[[ 1.  0.  1.]
 [ 0.  1.  0.]
 [ 0.  5.  0.]
 [ 0.  4. -3.]]
---------


In [ ]:
koeff_matrix = T(1,2,3, koeff_matrix)