# Aufgabenstellung 

Die Teilmenge $U \subset \mathbb{R}^4$ sei gegeben durch
\begin{equation}
U = \left \{ v | v = \begin{pmatrix} v_1 \\ v_2 \\ v_3 \\ v_4 \end{pmatrix} \text{ und } v_1 − v_2 + v_3 = 0 \text{ und } v_2 + 2v_3 − v_4 = 0 \right \}
\end{equation}
<br>
1. Zeigen Sie, dass $U$ ein Unterraum von $\mathbb{R}^4$ ist.
2. Bestimmen Sie eine Basis von $U$, und berechnen Sie die Dimension von $U$.
3. Ergänzen Sie die von Ihnen gefundene Basis von $U$ zu einer Basis von $\mathbb{R}^4$.

# Zeigen Sie, dass $U$ ein Unterraum von $\mathbb{R}^4$ ist.

## Notwendige Definitionen

### Unterraumkriterium

Sei $U$ eine Teilmenge eines Vektorraums $V$ über $\mathbb{K}$. Folgende Aussagen sind äquivalent:
1. $U$ ist ein Unterraum von $V$ .
2. Es gelten folgende Regeln:<br>
    2.1 Das Nullelement aus $V$ liegt in $U$, und<br>
    2.2 für alle $u_1$ , $u_2 \in U$ gilt $u_1 + u_2 \in U$, und <br>
    2.3 für alle $a \in \mathbb{K}$ und alle $u \in U$ gilt $au \in U$ .

Seien $x = \begin{pmatrix} x_1 \\ x_2 \\ x_3 \\ x_4 \end{pmatrix}$ und $y = \begin{pmatrix} y_1 \\ y_2 \\ y_3 \\ y_4 \end{pmatrix} \in U$, so gilt

## Unterelement aus $V$ liegt in $U$

Falls $x, y = \{0\}$ so ist $x + y = \{0\}$
\begin{equation}
\begin{pmatrix} 0 \\ 0 \\ 0 \\ 0 \end{pmatrix}  + \begin{pmatrix} 0 \\ 0 \\ 0 \\ 0 \end{pmatrix} = \begin{pmatrix} 0 \\ 0 \\ 0 \\ 0 \end{pmatrix}
\end{equation}
<br>
<br>
Da $\mathbb{R}^4$ einen Körper definiert so gilt für ein beliebiges Element $x \in V \neq \{0\}$: <br>
<br>
\begin{equation}
\begin{pmatrix} 0 \\ 0 \\ 0 \\ 0 \end{pmatrix} * \begin{pmatrix} x_1 \\ x_2 \\ x_3 \\ x_4 \end{pmatrix} = \begin{pmatrix} x_1 \\ x_2 \\ x_3 \\ x_4 \end{pmatrix} * \begin{pmatrix} 0 \\ 0 \\ 0 \\ 0 \end{pmatrix} = \begin{pmatrix} 0 \\ 0 \\ 0 \\ 0 \end{pmatrix} 
\end{equation}
<br>
und
<br>
\begin{equation}
\begin{pmatrix} 0 \\ 0 \\ 0 \\ 0 \end{pmatrix} + \begin{pmatrix} x_1 \\ x_2 \\ x_3 \\ x_4 \end{pmatrix} = \begin{pmatrix} x_1 \\ x_2 \\ x_3 \\ x_4 \end{pmatrix} + \begin{pmatrix} 0 \\ 0 \\ 0 \\ 0 \end{pmatrix} = \begin{pmatrix} x_1 \\ x_2 \\ x_3 \\ x_4 \end{pmatrix}
\end{equation}


## Für alle $u_1$ , $u_2 \in U$ gilt $u_1 + u_2 \in U$

\begin{equation}
 \begin{pmatrix} x_1 \\ x_2 \\ x_3 \\ x_4 \end{pmatrix} + \begin{pmatrix} y_1 \\ y_2 \\ y_3 \\ y_4 \end{pmatrix} = \begin{pmatrix} x_1 + y_1  \\ x_2 + y_2 \\ x_3 + y_4 \\ x_3 + y_4 \end{pmatrix}
\end{equation}
da, falls <br>

\begin{equation}
x_1 − x_2 + x_3 = 0 \\ 
x_2 + 2x_3 − x_4 = 0\\
y_1 − y_2 + y_3 = 0 \\ 
y_2 + 2y_3 − y_4 = 0
\end{equation}
so ist auch <br>
\begin{equation}
(x_1 + y_1) - (x_2 + y_2) + (x_3 + y_3) = 0 \\
(x_2 + y_2) + (2x_3 + 2y_3) - (x_4 + y_4) = 0
\end{equation}


## Für alle $a \in \mathbb{K}$ und alle $u \in U$ gilt $au \in U$


sei $a$ beliebiges Element \in \mathbb{K} so ist
\begin{equation}
a * \begin{pmatrix} x_1 \\ x_2 \\ x_3 \\ x_4 \end{pmatrix} =
\begin{pmatrix} a* x_1 \\ a * x_2 \\ a * x_3  \\ a * x_4 \end{pmatrix}
\end{equation}
<br>
und es ist
<br>
\begin{equation}
ax_1 − ax_2 + ax_3 = 0
\end{equation}
\begin{equation} 
ax_2 + 2ax_3 − ax_4 = 0
\end{equation}

# Bestimme eine Basis von $U$ und berechne die Dimension von $U$.

## Basis von $U$

1. Überführung von U in Gleichungssystem
\begin{equation}
v_1 − v_2 + v_3 + 0v_4= 0\\
0v_1 + v_2 + 2v_3 − v_4 = 0
\end{equation}
<br>
2. Umformung nach $v_2$ und $v_4$
\begin{equation}
v_2 = v_1 + v_3 \\
v_4 = v_2 + 2v_3
\end{equation}
<br>
3. Ableitung der Basis
<br>
$B= \left \{ \begin{pmatrix} v_1 \\ v_1 + v_3 \\ v_3 \\ v_2+2v_3 \end{pmatrix} \right \}$
<br>
oder
<br>
$B= \left \{ v_1 *\begin{pmatrix} 1 \\ 1 \\ 0 \\ 0 \end{pmatrix} + v_3 *\begin{pmatrix} 0 \\ 1 \\ 1 \\ 2 \end{pmatrix} | v_1, v_3 \in \mathbb{R}^4 \right \}$
<br>
oder
<br>
$B= \left \{\begin{pmatrix} 1 \\ 1 \\ 0 \\ 0 \end{pmatrix}, \begin{pmatrix} 0 \\ 1 \\ 1 \\ 2 \end{pmatrix} \right \}$

## Dimension von $U$

Die Anzahl frei wählbarer Variablen innerhalb der Basis ist 2. $Dim(V) = 2$


# Ergänze gefundene Basis von $U$ zu einer Basis von $\mathbb{R}^4$

1. Überfühung der gefundenen Basis in Koeffizientenmatrix
\begin{equation}
\begin{pmatrix} 
1 & 1 & 0 & 0 & | & 0 \\
0 & 1 & 1 & 2 & | & 0 \\
\end{pmatrix}
\end{equation}
<br>
2. Ermittlung der Treppennormalform

In [31]:
import numpy as np
np.set_printoptions(precision=3)
#define elementary operations on matrices

# add value row j * var to row i (T_ij(var))
def T(i, j, var, matrix):
    matrix_t = np.copy(matrix)
    matrix_t[i-1] = matrix_t[i-1] + matrix[j-1] * var
    print("---------")
    print("T", i, j, var)
    print(matrix_t)
    print("---------")
    return matrix_t

koeff_matrix = np.array([[1, 1, 0, 0 ], [0, 1, 1, 2]], dtype='float')
print(koeff_matrix)
koeff_matrix = T(1,2,-1, koeff_matrix)    

[[ 1.  1.  0.  0.]
 [ 0.  1.  1.  2.]]
---------
('T', 1, 2, -1)
[[ 1.  0. -1. -2.]
 [ 0.  1.  1.  2.]]
---------


Koeffizientenmatrix in Treppennormalform:
<br>
\begin{equation}
\begin{pmatrix} 
1 & 0 & -1 & -2\\
0 & 1 & 1 & 2\\
\end{pmatrix}
\end{equation}
<br>
3. Erweiterung um Nullzeilen
\begin{equation}
\begin{pmatrix} 
1 & 0 & -1 & -2\\
0 & 1 & 1 & 2\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0\\
\end{pmatrix}
\end{equation}
<br>
4. Einsetzen von $-1$ als Diagonalelemente in Nullzeilen
\begin{equation}
\begin{pmatrix} 
1 & 0 & -1 & -2\\
0 & 1 & 1 & 2\\
0 & 0 & -1 & 0\\
0 & 0 & 0 & -1\\
\end{pmatrix}
\end{equation}
<br>
5. Ableiten der zusätzlichen Vektoren
\begin{equation}
\left \{\begin{pmatrix} 0 \\ 0 \\ -1 \\ 0 \end{pmatrix}, \begin{pmatrix} 0 \\ 0 \\ 0 \\ -1 \end{pmatrix} \right \}
\end{equation}
<br>
6. Basis über $\mathbb{R}^4$

\begin{equation}
B = 
\left \{
\begin{pmatrix} 1 \\ 1 \\ 0 \\ 0 \end{pmatrix}, 
\begin{pmatrix} 0 \\ 1 \\ 1 \\ 2 \end{pmatrix}, 
\begin{pmatrix} 0 \\ 0 \\ -1 \\ 0 \end{pmatrix}, 
\begin{pmatrix} 0 \\ 0 \\ 0 \\ -1 \end{pmatrix} 
\right \}
\end{equation}